### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by cathalgarvey** [readbrent/HatespeechAnalysis#1]
Hey, interesting work, thank you for sharing it with the notebook. :)

The labelled dataset that you made for this project could be very useful for related work, do you still have access to it, to share?

**Comment by readbrent** [comment]
Thanks!

I got the dataset from CrowdFlower (Who have a lot of awesome datasets). Specifically, I got it from [here!](https://www.crowdflower.com/wp-content/uploads/2016/03/twitter-hate-speech-classifier-DFE-a845520.csv)

I'll add this into the description for more clear attribution :)

**Comment by cathalgarvey** [comment]
Thanks! :)

On 16 May 2017 01:45:24 GMT+01:00, readbrent <notifications@github.com> wrote:
>Thanks!
>
>I got the dataset from CrowdFlower (Who have a lot of awesome
>datasets). Specifically, I got it from
>[here!](https://www.crowdflower.com/wp-content/uploads/2016/03/twitter-hate-speech-classifier-DFE-a845520.csv)
>
>I'll add this into the description for more clear attribution :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/readbrent/HatespeechAnalysis/issues/1#issuecomment-301643503

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
